# Generated by Django 3.2.15 on 2022-09-26 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_score', models.IntegerField(default=0)),
                ('expert_score', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=1024)),
                ('order_price', models.IntegerField(default=0)),
                ('is_arrived', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
                ('comission', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('address', models.TextField(max_length=1024)),
                ('payment', models.CharField(choices=[('CA', 'Cash'), ('CR', 'Credit')], default='CR', max_length=2)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
